// Auth action types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// Settings action types
export const SET_SETTINGS = 'SET_SETTINGS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

// Exam action types
export const FETCH_EXAMS_REQUEST = 'FETCH_EXAMS_REQUEST';
export const FETCH_EXAMS_SUCCESS = 'FETCH_EXAMS_SUCCESS';
export const FETCH_EXAMS_FAILURE = 'FETCH_EXAMS_FAILURE';
export const SET_CURRENT_EXAM = 'SET_CURRENT_EXAM';
export const SET_EXAM_ANSWER = 'SET_EXAM_ANSWER';
export const SUBMIT_EXAM_REQUEST = 'SUBMIT_EXAM_REQUEST';
export const SUBMIT_EXAM_SUCCESS = 'SUBMIT_EXAM_SUCCESS';
export const SUBMIT_EXAM_FAILURE = 'SUBMIT_EXAM_FAILURE';

// Reading specific
export const FETCH_READING_REQUEST = 'FETCH_READING_REQUEST';
export const FETCH_READING_SUCCESS = 'FETCH_READING_SUCCESS';
export const FETCH_READING_FAILURE = 'FETCH_READING_FAILURE';

// Listening specific
export const FETCH_LISTENING_REQUEST = 'FETCH_LISTENING_REQUEST';
export const FETCH_LISTENING_SUCCESS = 'FETCH_LISTENING_SUCCESS';
export const FETCH_LISTENING_FAILURE = 'FETCH_LISTENING_FAILURE';
export const SET_AUDIO_PLAYING = 'SET_AUDIO_PLAYING';

// Speaking specific
export const FETCH_SPEAKING_REQUEST = 'FETCH_SPEAKING_REQUEST';
export const FETCH_SPEAKING_SUCCESS = 'FETCH_SPEAKING_SUCCESS';
export const FETCH_SPEAKING_FAILURE = 'FETCH_SPEAKING_FAILURE';
export const START_RECORDING = 'START_RECORDING';
export const STOP_RECORDING = 'STOP_RECORDING';
export const SAVE_RECORDING = 'SAVE_RECORDING';
export const ANALYZE_SPEAKING_REQUEST = 'ANALYZE_SPEAKING_REQUEST';
export const ANALYZE_SPEAKING_SUCCESS = 'ANALYZE_SPEAKING_SUCCESS';
export const ANALYZE_SPEAKING_FAILURE = 'ANALYZE_SPEAKING_FAILURE';

// Writing specific
export const FETCH_WRITING_REQUEST = 'FETCH_WRITING_REQUEST';
export const FETCH_WRITING_SUCCESS = 'FETCH_WRITING_SUCCESS';
export const FETCH_WRITING_FAILURE = 'FETCH_WRITING_FAILURE';
export const SAVE_ESSAY = 'SAVE_ESSAY';
export const ANALYZE_ESSAY_REQUEST = 'ANALYZE_ESSAY_REQUEST';
export const ANALYZE_ESSAY_SUCCESS = 'ANALYZE_ESSAY_SUCCESS';
export const ANALYZE_ESSAY_FAILURE = 'ANALYZE_ESSAY_FAILURE';

// Vocabulary action types
export const FETCH_VOCABULARY_REQUEST = 'FETCH_VOCABULARY_REQUEST';
export const FETCH_VOCABULARY_SUCCESS = 'FETCH_VOCABULARY_SUCCESS';
export const FETCH_VOCABULARY_FAILURE = 'FETCH_VOCABULARY_FAILURE';
export const ADD_VOCABULARY = 'ADD_VOCABULARY';
export const REMOVE_VOCABULARY = 'REMOVE_VOCABULARY';
export const UPDATE_VOCABULARY = 'UPDATE_VOCABULARY';
export const MARK_VOCABULARY_LEARNED = 'MARK_VOCABULARY_LEARNED';

// Progress action types
export const FETCH_PROGRESS_REQUEST = 'FETCH_PROGRESS_REQUEST';
export const FETCH_PROGRESS_SUCCESS = 'FETCH_PROGRESS_SUCCESS';
export const FETCH_PROGRESS_FAILURE = 'FETCH_PROGRESS_FAILURE';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
